name: AI Code Review

on:
  push:  # Runs on every push to the repository
    branches:
      - main
      - dev  # Add other branches as needed

  pull_request:  # Runs when a PR is opened or updated
    types:
      - opened
      - synchronize

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run AI Code Reviewer
        run: node src/ai-reviewer.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_


